export const DOMAINS = [
  { id:'D0', label:'AI Fluency & Power Use', weight:0,  color:'#7C3AED' },
  { id:'DA', label:'API & RAG Basics',       weight:0,  color:'#0E7490' },
  { id:'D1', label:'Agentic Architecture',   weight:27, color:'#C8421A' },
  { id:'D2', label:'Tool Design & MCP',      weight:20, color:'#1A6BC8' },
  { id:'D3', label:'Claude Code Config',     weight:20, color:'#D4621A' },
  { id:'D4', label:'Prompt Engineering',     weight:20, color:'#2A7A3A' },
  { id:'D5', label:'Context & Reliability',  weight:15, color:'#6B21A8' },
]

export const WEEKS = [
  // ─── STAGE 1: AI Fluency ───────────────────────────────────────────────────
  {
    id:1, phase:0, phaseLabel:'Prerequisites',
    title:'AI Fluency & How Claude Works', dates:'Week 1',
    domain:'Stage 1 — No code needed', color:'#7C3AED', build:'No build — pure learning',
    tasks:[
      {id:'w0d1t1',day:1,date:'Day 1',label:'AI Basics',type:'read',domain:'D0',text:'Complete "AI Capabilities and Limitations" course on Anthropic Academy — understand what LLMs can and cannot do'},
      {id:'w0d1t2',day:1,date:'Day 1',label:'AI Basics',type:'read',domain:'D0',text:'Note: hallucinations, reasoning limits, context windows, and non-determinism — these come up in every exam domain'},
      {id:'w0d2t1',day:2,date:'Day 2',label:'AI Fluency',type:'read',domain:'D0',text:'Complete "AI Fluency: Framework & Foundations" course — responsible AI, collaboration with AI, ethical use'},
      {id:'w0d2t2',day:2,date:'Day 2',label:'AI Fluency',type:'read',domain:'D0',text:'Reflect: where would AI fail in your current work? Write 3 scenarios — good intuition for exam traps'},
      {id:'w0d3t1',day:3,date:'Day 3',label:'Claude 101',type:'read',domain:'D0',text:'Complete "Claude 101" course — projects, artifacts, memory, conversation management'},
      {id:'w0d3t2',day:3,date:'Day 3',label:'Claude 101',type:'read',domain:'D0',text:'Create a free claude.ai account if you don\'t have one. Explore Projects and try a few conversations.'},
      {id:'w0d4t1',day:4,date:'Day 4',label:'Prompting Basics',type:'read',domain:'D0',text:'Read Anthropic\'s Prompt Engineering Overview docs — understand what a system prompt is, how roles work'},
      {id:'w0d4t2',day:4,date:'Day 4',label:'Prompting Basics',type:'build',domain:'D0',text:'Try the Google Sheets interactive prompting tutorial — no code needed, builds prompt intuition fast'},
      {id:'w0d5t1',day:5,date:'Day 5',label:'Practice',type:'test',domain:'D0',text:'Self-quiz: what is a context window? What is a token? What is a system prompt? Explain each in plain English.'},
      {id:'w0d6t1',day:6,date:'Day 6',label:'Review',type:'review',domain:'D0',text:'Review AI Fluency notes. Identify any concept still unclear — re-read that section before moving to Week 2.'},
      {id:'w0d7t1',day:7,date:'Day 7',label:'Rest',type:'rest',domain:'D0',text:'Rest day. You\'re building a foundation — don\'t rush it.'},
    ],
    materials:[
      {type:'course',icon:'🎓',title:'AI Capabilities and Limitations',url:'https://anthropic.skilljar.com/ai-capabilities-and-limitations',desc:'Free · Anthropic Academy. How LLMs work, what they can\'t do, hallucinations, reasoning limits.'},
      {type:'course',icon:'🎓',title:'AI Fluency: Framework & Foundations',url:'https://anthropic.skilljar.com/ai-fluency-framework-foundations',desc:'Free · Anthropic Academy. Responsible AI collaboration, ethics, effective + safe use.'},
      {type:'course',icon:'🎓',title:'Claude 101',url:'https://anthropic.skilljar.com/claude-101',desc:'Free · Anthropic Academy. 13 lessons, ~3hrs. Core Claude features, projects, artifacts, memory.'},
      {type:'read',icon:'📄',title:'Prompt Engineering Overview',url:'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview',desc:'Official Anthropic docs. System prompts, roles, prompting concepts — no code required to read.'},
      {type:'practice',icon:'📊',title:'Interactive Prompting Tutorial (Google Sheets)',url:'https://docs.google.com/spreadsheets/d/19jzLgRruG9kjUQNKtCg1ZjdD6l6weA6qRXG5zLIAhC8',desc:'Free · No code needed. Hands-on prompting exercises in a spreadsheet.'},
      {type:'supplementary',icon:'🎬',title:'Claude AI: The AI Assistant You\'ll Actually Use',url:'https://www.udemy.com/course/claude-ai-the-ai-assistant-youll-actually-use/',desc:'Optional · Udemy · ⭐4.5 · 2,602 ratings · 8hrs. Practical Claude usage for real-world tasks.',paid:true},
      {type:'supplementary',icon:'🎬',title:'Claude for Beginners: AI in Business & Automation',url:'https://www.udemy.com/course/claude-pro-mastery-ai-for-business-marketing-automation/',desc:'Optional · Udemy · ⭐4.3 · 191 ratings · 16hrs. Business and marketing use cases.',paid:true},
    ],
    concepts:[
      {type:'rule',title:'What is a token?',body:'A token ≈ 0.75 words. "Hello world" = 3 tokens.\nContext window = max tokens Claude can process at once.\nClaude 3.5 Sonnet: 200K token context window.\n\nWhy it matters: long conversations + big docs eat context fast.'},
      {type:'compare',title:'Hallucination vs correct behaviour',bad:{label:'✗ Hallucination',text:'Claude confidently states a fact that is wrong — a made-up citation, wrong date, fake API. Happens more with obscure or recent facts.'},good:{label:'✓ Correct behaviour',text:'Claude says "I\'m not certain" or asks for clarification. Design systems to verify Claude outputs, not blindly trust them.'}},
      {type:'tip',title:'🎯 Foundation Tip',body:'Everything in the CCA exam builds on these fundamentals. If you don\'t understand why LLMs are non-deterministic, you won\'t understand why exam answers favour deterministic code (hooks, schemas) over probabilistic prompts.'},
    ]
  },
  // ─── STAGE 2: Power User ──────────────────────────────────────────────────
  {
    id:2, phase:0, phaseLabel:'Prerequisites',
    title:'Claude as a Power User', dates:'Week 2',
    domain:'Stage 2 — Claude.ai account needed', color:'#0891B2', build:'No build — hands-on Claude UI',
    tasks:[
      {id:'w0b1t1',day:1,date:'Day 1',label:'Cowork',type:'read',domain:'D0',text:'Complete "Introduction to Claude Cowork" course — task loops, plugins, skills, file and research workflows'},
      {id:'w0b1t2',day:1,date:'Day 1',label:'Cowork',type:'build',domain:'D0',text:'In Claude.ai: create a Project, upload a document, ask Claude to summarise and extract key points'},
      {id:'w0b2t1',day:2,date:'Day 2',label:'Prompting',type:'read',domain:'D0',text:'Read Anthropic Prompting Best Practices docs — XML tags, chain-of-thought, role prompting, few-shot'},
      {id:'w0b2t2',day:2,date:'Day 2',label:'Prompting',type:'build',domain:'D0',text:'Try the GitHub Interactive Prompt Engineering Tutorial — work through all exercises'},
      {id:'w0b3t1',day:3,date:'Day 3',label:'Claude Code 101',type:'read',domain:'D0',text:'Complete "Claude Code 101" course — understand what Claude Code is before touching the API'},
      {id:'w0b4t1',day:4,date:'Day 4',label:'Practice',type:'build',domain:'D0',text:'Build a useful prompt for your own work: multi-turn conversation, system prompt with clear persona and constraints'},
      {id:'w0b4t2',day:4,date:'Day 4',label:'Practice',type:'build',domain:'D0',text:'Test the same prompt with and without a system prompt — observe the difference in output quality'},
      {id:'w0b5t1',day:5,date:'Day 5',label:'Test',type:'test',domain:'D0',text:'Self-quiz: what is few-shot prompting? Chain-of-thought? Role prompting? XML structuring? Give an example of each.'},
      {id:'w0b6t1',day:6,date:'Day 6',label:'Review',type:'review',domain:'D0',text:'Review all prompting notes. Flag any technique you couldn\'t explain — re-read that section.'},
      {id:'w0b7t1',day:7,date:'Day 7',label:'Rest',type:'rest',domain:'D0',text:'Rest. Next week is the first coding week — make sure you have Python 3.9+ installed and an API key ready.'},
    ],
    materials:[
      {type:'course',icon:'🎓',title:'Introduction to Claude Cowork',url:'https://anthropic.skilljar.com/introduction-to-claude-cowork',desc:'Free · Anthropic Academy. Task loops, plugins, file workflows, multi-step work.'},
      {type:'course',icon:'🎓',title:'Claude Code 101',url:'https://anthropic.skilljar.com/claude-code-101',desc:'Free · Anthropic Academy. What Claude Code is, daily dev workflow basics.'},
      {type:'read',icon:'📄',title:'Prompting Best Practices',url:'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices',desc:'Official Anthropic docs. XML, CoT, role prompting, few-shot — the techniques tested in the exam.'},
      {type:'practice',icon:'💻',title:'GitHub Interactive Prompt Engineering Tutorial',url:'https://github.com/anthropics/prompt-eng-interactive-tutorial',desc:'Free · Hands-on exercises. Best way to internalise prompting techniques before the exam.'},
      {type:'read',icon:'📚',title:'Get API Key — Anthropic Console',url:'https://platform.claude.com/settings/keys',desc:'Prerequisite for Week 3. Create your account and API key before moving on.'},
      {type:'supplementary',icon:'🎬',title:'Claude - Master Claude Cowork, Claude Code, Skills & Plugins',url:'https://www.udemy.com/course/claude-code-cowork-course/',desc:'Optional · Udemy · ⭐4.7 · 160 ratings · 15.5hrs. Deep dive on Cowork and Claude Code UI.',paid:true},
      {type:'supplementary',icon:'🎬',title:'Mastering Claude Cowork & AI Agents in 5 hours',url:'https://www.udemy.com/course/mastering-claude-cowork-ai-agents/',desc:'Optional · Udemy · ⭐4.7 · 176 ratings · 5hrs. Zero coding required.',paid:true},
    ],
    concepts:[
      {type:'rule',title:'System prompt vs user message',body:'System prompt: persistent instructions, persona, constraints — set once per session\nUser message: the conversation turn\n\nThe system prompt is what architects tune. It defines Claude\'s behaviour boundary.'},
      {type:'compare',title:'Vague prompt vs structured prompt',bad:{label:'✗ Vague',text:'"Summarise this document." — Claude guesses format, length, audience, focus. Output is unpredictable.'},good:{label:'✓ Structured',text:'"Summarise this document in 3 bullet points for a non-technical manager. Focus on business impact only."'}},
      {type:'tip',title:'🎯 Power User Tip',body:'The CCA exam tests whether you know WHEN to use prompting vs code. Power user stage teaches you prompting limits — that knowledge directly drives exam answers about hooks, schemas, and deterministic enforcement.'},
    ]
  },
  // ─── STAGE 3: API Developer ───────────────────────────────────────────────
  {
    id:3, phase:0, phaseLabel:'Prerequisites',
    title:'API Basics, RAG & MCP Intro', dates:'Week 3',
    domain:'Stage 3 — API key + Python needed', color:'#0E7490', build:'Build: first API call + simple RAG',
    tasks:[
      {id:'w0c1t1',day:1,date:'Day 1',label:'API Setup',type:'build',domain:'DA',text:'Install Anthropic Python SDK: pip install anthropic. Run the quickstart — make your first Messages API call.'},
      {id:'w0c1t2',day:1,date:'Day 1',label:'API Setup',type:'read',domain:'DA',text:'Read API docs: messages.create(), model selection, max_tokens, system, messages array structure'},
      {id:'w0c2t1',day:2,date:'Day 2',label:'API Course',type:'read',domain:'DA',text:'Start "Building with the Claude API" course (Anthropic Academy) — complete Getting Started section (16 lessons)'},
      {id:'w0c2t2',day:2,date:'Day 2',label:'API Course',type:'read',domain:'DA',text:'Complete Prompt Engineering & Evaluation section (16 lessons) — automated testing, evals framework'},
      {id:'w0c3t1',day:3,date:'Day 3',label:'Tool Use',type:'read',domain:'DA',text:'Complete Tool Use section of the API course (14 lessons) — function calling, tool schemas, multi-turn tools'},
      {id:'w0c3t2',day:3,date:'Day 3',label:'Tool Use',type:'build',domain:'DA',text:'Build a simple tool-calling agent: define one tool, handle tool_use stop_reason, return tool_result'},
      {id:'w0c4t1',day:4,date:'Day 4',label:'RAG',type:'read',domain:'DA',text:'Complete RAG section of the API course (10 lessons) — chunking, embeddings, hybrid search, reranking'},
      {id:'w0c4t2',day:4,date:'Day 4',label:'RAG',type:'read',domain:'DA',text:'Complete MCP section of the API course (12 lessons) — MCP servers, clients, tools, resources'},
      {id:'w0c5t1',day:5,date:'Day 5',label:'MCP Intro',type:'read',domain:'DA',text:'Complete "Introduction to MCP" course (Anthropic Academy) — build an MCP server from scratch in Python'},
      {id:'w0c5t2',day:5,date:'Day 5',label:'MCP Intro',type:'read',domain:'DA',text:'Read modelcontextprotocol.io — understand the 3 core primitives: tools, resources, prompts'},
      {id:'w0c6t1',day:6,date:'Day 6',label:'Agents',type:'read',domain:'DA',text:'Complete Agents & Workflows section of the API course (11 lessons) — parallel execution, chaining, routing'},
      {id:'w0c7t1',day:7,date:'Day 7',label:'Rest',type:'rest',domain:'DA',text:'Rest. You\'re now ready for the CCA-specific weeks. The exam builds directly on what you just learned.'},
    ],
    materials:[
      {type:'course',icon:'🎓',title:'Building with the Claude API',url:'https://anthropic.skilljar.com/claude-with-the-anthropic-api',desc:'Free · Anthropic Academy · 84 lessons · 8.1hrs · Certificate on completion. The most important course for CCA prep.'},
      {type:'course',icon:'🎓',title:'Introduction to Model Context Protocol',url:'https://anthropic.skilljar.com/introduction-to-model-context-protocol',desc:'Free · Anthropic Academy. Build MCP servers from scratch. Tools, resources, prompts primitives.'},
      {type:'course',icon:'🎓',title:'MCP Advanced Topics',url:'https://anthropic.skilljar.com/model-context-protocol-advanced-topics',desc:'Free · Anthropic Academy. Sampling, notifications, file system access, transport mechanisms.'},
      {type:'read',icon:'📚',title:'Claude API Quickstart',url:'https://platform.claude.com/docs/en/get-started',desc:'Official getting started guide. First API call, SDK setup, key concepts.'},
      {type:'read',icon:'📚',title:'Anthropic Cookbook — Code Patterns',url:'https://platform.claude.com/cookbooks',desc:'Free · Official code samples and production patterns. Reference throughout Stages 3 and 4.'},
      {type:'read',icon:'📚',title:'Anthropic Quickstart Projects',url:'https://github.com/anthropics/anthropic-quickstarts',desc:'Free · GitHub. Deployable starter apps — see how production patterns look end-to-end.'},
      {type:'supplementary',icon:'🎬',title:'Claude Code - The Practical Guide (Academind)',url:'https://www.udemy.com/course/claude-code-the-practical-guide/',desc:'Optional · Udemy · ⭐4.6 · 5,935 ratings · 3hrs. Best-rated practical Claude Code course.',paid:true},
      {type:'supplementary',icon:'🎬',title:'The Complete Claude Code & Claude Cowork Masterclass',url:'https://www.udemy.com/course/claude-aiagents-cowork-masterclass/',desc:'Optional · Udemy · ⭐4.6 · 865 ratings · 15hrs. Comprehensive developer + agent content.',paid:true},
    ],
    concepts:[
      {type:'rule',title:'Messages API structure',body:'client.messages.create(\n  model="claude-sonnet-4-6",\n  max_tokens=1024,\n  system="You are...",    # optional\n  messages=[\n    {"role":"user",   "content":"Hello"},\n    {"role":"assistant","content":"Hi!"},\n    {"role":"user",   "content":"Next turn"}\n  ]\n)'},
      {type:'compare',title:'RAG vs fine-tuning',bad:{label:'✗ Fine-tuning (wrong tool)',text:'Training the model on your data. Expensive, slow, knowledge becomes stale. Wrong choice for dynamic or frequently updated data.'},good:{label:'✓ RAG (right tool)',text:'Retrieve relevant chunks at query time, inject into context. Stays current, no training cost, auditable sources.'}},
      {type:'tip',title:'🎯 API Stage Tip',body:'The "Building with the Claude API" course is the closest thing to an official CCA study guide. Complete every section before Week 4 — many exam questions test exactly these patterns.'},
    ]
  },
  // ─── CCA EXAM WEEKS ───────────────────────────────────────────────────────
  {
    id:4, phase:1, phaseLabel:'Foundations',
    title:'Agentic Loops & Core API', dates:'Apr 19–25',
    domain:'Domain 1 · 27%', color:'#C8421A', build:'Build: minimal agentic loop',
    tasks:[
      {id:'w1d1t1',day:1,date:'Apr 19',label:'Orientation',type:'read',domain:'D1',text:'Download & read the official CCA Foundations exam guide PDF — map all 5 domains and 6 scenarios'},
      {id:'w1d1t2',day:1,date:'Apr 19',label:'Orientation',type:'read',domain:'D1',text:'Bookmark claudecertifications.com — study guide, domains, practice questions, anti-patterns pages'},
      {id:'w1d2t1',day:2,date:'Apr 20',label:'Loop Theory',type:'read',domain:'D1',text:'Read Domain 1.1: Agentic Loops & Core API — stop_reason "tool_use" vs "end_turn", loop lifecycle'},
      {id:'w1d2t2',day:2,date:'Apr 20',label:'Loop Theory',type:'read',domain:'D1',text:'Read Anthropic docs: Messages API, tool_use content blocks, stop_reason field'},
      {id:'w1d3t1',day:3,date:'Apr 21',label:'First Build',type:'build',domain:'D1',text:'Build: minimal agentic loop — implement while loop checking stop_reason, execute tools, append results'},
      {id:'w1d3t2',day:3,date:'Apr 21',label:'First Build',type:'build',domain:'D1',text:'Deliberately break it: try NL termination and see it fail. Confirm stop_reason is only reliable signal.'},
      {id:'w1d4t1',day:4,date:'Apr 22',label:'Anti-Patterns',type:'read',domain:'D1',text:'Study anti-patterns: NL termination, iteration caps, text content checks — understand WHY each fails'},
      {id:'w1d5t1',day:5,date:'Apr 23',label:'Practice Test',type:'test',domain:'D1',text:'Practice Test 1: Agentic Loops — 10 questions, strict 20-min timer, no lookups mid-test'},
      {id:'w1d6t1',day:6,date:'Apr 24',label:'Review',type:'review',domain:'D1',text:'Deep-review every wrong answer — re-read the relevant domain section for each miss, not just the answer'},
      {id:'w1d7t1',day:7,date:'Apr 25',label:'Rest',type:'rest',domain:'D1',text:'Rest + 20-min Anki review of Week 1 terms only'},
    ],
    materials:[
      {type:'read',icon:'📄',title:'Domain 1: Agentic Architecture & Orchestration',url:'https://claudecertifications.com/claude-certified-architect/domains/agentic-architecture',desc:'Full domain deep-dive. Read d1.1 this week.'},
      {type:'read',icon:'📄',title:'Official CCA Exam Guide',url:'https://claudecertifications.com/claude-certified-architect/exam-guide',desc:'Domain weights, exam format, 6 scenario overviews. Read in full on Day 1.'},
      {type:'read',icon:'📚',title:'Anthropic API Docs — Messages & Tool Use',url:'https://docs.anthropic.com/en/api/getting-started',desc:'stop_reason field, tool_use content blocks, message structure.'},
      {type:'course',icon:'🎓',title:'Claude 101 — claudecertifications.com',url:'https://claudecertifications.com/courses/claude-101',desc:'13 lessons, 3h. Start Day 4. Covers Claude fundamentals, projects, artifacts.'},
      {type:'practice',icon:'❓',title:'Practice Questions',url:'https://claudecertifications.com/claude-certified-architect/practice-questions',desc:'Filter to Domain 1. Do on Day 5.'},
      {type:'practice',icon:'⚠️',title:'Anti-Patterns Cheatsheet',url:'https://claudecertifications.com/claude-certified-architect/anti-patterns',desc:'18 common wrong answers. Read after practice test on Day 6.'},
    ],
    concepts:[
      {type:'rule',title:'The only loop control signal',body:'stop_reason == "tool_use" → Claude needs a tool → keep looping\nstop_reason == "end_turn" → Claude is done → exit loop\n\nThis is the ONLY reliable signal. Nothing else.'},
      {type:'compare',title:'Anti-pattern vs correct',bad:{label:'✗ Anti-Pattern',text:'Parsing natural language: checking if response text contains "task complete" or "I\'m done" to exit the loop'},good:{label:'✓ Correct',text:'Checking stop_reason field: if response.stop_reason == "end_turn": break'}},
      {type:'tip',title:'🎯 Exam Tip',body:'The exam presents 3–4 loop termination options. Correct answer is always checking stop_reason. Eliminate any option that parses text, counts iterations, or monitors token counts.'},
    ]
  },
  {
    id:5, phase:1, phaseLabel:'Foundations',
    title:'Multi-Agent Orchestration & Sessions', dates:'Apr 26–May 2',
    domain:'Domain 1 · cont.', color:'#D4621A', build:'Build: coordinator + 2 subagents',
    tasks:[
      {id:'w2d1t1',day:1,date:'Apr 26',label:'Orchestration',type:'read',domain:'D1',text:'Read Domain 1.2: Hub-and-spoke architecture — coordinator role, why flat multi-agent fails, context isolation'},
      {id:'w2d2t1',day:2,date:'Apr 27',label:'Task Tool',type:'read',domain:'D1',text:'Read: Task tool for subagent spawning — allowedTools must include "Task", parallel execution via multiple Task calls'},
      {id:'w2d2t2',day:2,date:'Apr 27',label:'Task Tool',type:'read',domain:'D1',text:'Read: fork_session for branched exploration — how it differs from --resume'},
      {id:'w2d3t1',day:3,date:'Apr 28',label:'Build',type:'build',domain:'D1',text:'Build: coordinator + 2 subagents — pass explicit context per subagent, no shared state, verify isolation'},
      {id:'w2d4t1',day:4,date:'Apr 29',label:'Hooks',type:'read',domain:'D1',text:'Read Domain 1.3: PostToolUse hooks — deterministic vs probabilistic enforcement'},
      {id:'w2d4t2',day:4,date:'Apr 29',label:'Sessions',type:'read',domain:'D1',text:'Read Domain 1.4: Session management — --resume, fork_session, named sessions, stale context'},
      {id:'w2d5t1',day:5,date:'Apr 30',label:'Practice Test',type:'test',domain:'D1',text:'Practice Test 2: Multi-Agent Systems — 10 questions, timed'},
      {id:'w2d6t1',day:6,date:'May 1',label:'Review',type:'review',domain:'D1',text:'Review wrong answers — categorise each miss: orchestration gap, context gap, or tool access gap'},
      {id:'w2d7t1',day:7,date:'May 2',label:'Rest',type:'rest',domain:'D1',text:'Rest + Anki — add hub-and-spoke, fork_session, stop_reason cards'},
    ],
    materials:[
      {type:'read',icon:'📄',title:'Domain 1.2–1.4: Orchestration, Hooks, Sessions',url:'https://claudecertifications.com/claude-certified-architect/domains/agentic-architecture',desc:'Complete Domain 1 — all four subtopics.'},
      {type:'supplementary',icon:'📝',title:'Rick Hightower — CCA Guide Parts 1 & 2',url:'https://pub.towardsai.net/claude-certified-architect-the-complete-guide-to-passing-the-cca-foundations-exam-9665ce7342a8',desc:'Part 2 covers multi-agent scenarios in depth.'},
    ],
    concepts:[
      {type:'compare',title:'Hub-and-spoke vs flat multi-agent',bad:{label:'✗ Flat',text:'All agents share context. State pollutes. Tools overlap. No synthesis point. Fails at scale.'},good:{label:'✓ Hub-and-Spoke',text:'Coordinator delegates with scoped context. Subagents have 4–5 tools each. Results return to coordinator.'}},
      {type:'rule',title:'Critical: context passing rule',body:'Pass ONLY the context specific to each subagent\'s task.\nNever share the full coordinator conversation history.\nExcess context = wasted tokens + confused subagent.'},
      {type:'compare',title:'Hooks: enforcement rule',bad:{label:'✗ Prompt-based',text:'"Never process refunds over $500" in system prompt. Probabilistic — model can ignore it.'},good:{label:'✓ Hook-based',text:'PostToolUse hook blocking refund.amount > 500 in code. 100% reliable.'}},
      {type:'tip',title:'🎯 Exam Tip',body:'Any question about enforcing a critical business rule → correct answer is programmatic hooks. Any answer using prompt instructions for enforcement is wrong.'},
    ]
  },
  {
    id:6, phase:2, phaseLabel:'Applied Knowledge',
    title:'Tool Design & MCP Integration', dates:'May 3–9',
    domain:'Domain 2 · 20%', color:'#1A6BC8', build:'Build: working MCP server',
    tasks:[
      {id:'w3d1t1',day:1,date:'May 3',label:'Tool Descriptions',type:'read',domain:'D2',text:'Read Domain 2.1–2.2: Tool description best practices — input formats, examples, edge cases, failure modes'},
      {id:'w3d2t1',day:2,date:'May 4',label:'Error Responses',type:'read',domain:'D2',text:'Read Domain 2.3–2.4: Structured error responses (isError, errorCategory, isRetryable) + tool distribution: 4–5 max'},
      {id:'w3d3t1',day:3,date:'May 5',label:'MCP Config',type:'read',domain:'D2',text:'Read Domain 2.5: MCP config — .mcp.json (project) vs ~/.claude.json (user level)'},
      {id:'w3d3t2',day:3,date:'May 5',label:'Built-in Tools',type:'read',domain:'D2',text:'Read: Built-in tools — Read, Write, Edit, Bash, Grep, Glob — know Grep vs Glob distinction cold'},
      {id:'w3d4t1',day:4,date:'May 6',label:'Build',type:'build',domain:'D2',text:'Build: working MCP server with 2–3 tools, proper descriptions, structured error responses on all 4 categories'},
      {id:'w3d5t1',day:5,date:'May 7',label:'Practice Test',type:'test',domain:'D2',text:'Practice Test 3: Tool Design & MCP — 10 questions, timed'},
      {id:'w3d6t1',day:6,date:'May 8',label:'Review',type:'review',domain:'D2',text:'Review wrong answers. Re-read Grep vs Glob and isRetryable vs non-retryable error categories.'},
      {id:'w3d7t1',day:7,date:'May 9',label:'Rest',type:'rest',domain:'D2',text:'Rest + Anki — add MCP config, tool error types, Grep/Glob distinction'},
    ],
    materials:[
      {type:'read',icon:'📄',title:'Domain 2: Tool Design & MCP Integration',url:'https://claudecertifications.com/claude-certified-architect/domains/tool-design-mcp',desc:'Full domain — tool descriptions, error responses, MCP config.'},
      {type:'read',icon:'📚',title:'Anthropic MCP Documentation',url:'https://docs.anthropic.com/en/docs/agents-and-tools/mcp',desc:'Official MCP server setup, configuration files, tool registration.'},
      {type:'read',icon:'📚',title:'modelcontextprotocol.io — MCP Spec',url:'https://modelcontextprotocol.io/docs',desc:'The MCP specification.'},
      {type:'course',icon:'🎓',title:'Claude Code in Action — MCP Servers',url:'https://claudecertifications.com/courses/claude-code-in-action',desc:'Start the MCP Servers section this week.'},
    ],
    concepts:[
      {type:'rule',title:'MCP config file location',body:'.mcp.json — project-level, committed to repo, shared with team\n~/.claude.json — user-level, personal tools, not shared\n\nWrong location = tools not available where expected.'},
      {type:'rule',title:'Structured error response fields',body:'isError: true — signals tool failure\nerrorCategory — "not_found"|"permission_denied"|"rate_limited"|"internal_error"\nisRetryable: true/false — tells agent whether to retry\n\nAll 3 fields required.'},
      {type:'compare',title:'Grep vs Glob',bad:{label:'Glob — find files',text:'Pattern matching on file paths. Use to find files matching *.py or src/**/*.ts'},good:{label:'Grep — search content',text:'Search inside file content. Find lines matching a pattern across files.'}},
      {type:'tip',title:'🎯 Exam Tip',body:'Tool descriptions are more important than most people realise — they are what Claude uses to decide which tool to call and how. Vague descriptions = wrong tool selection = system failure.'},
    ]
  },
  {
    id:7, phase:2, phaseLabel:'Applied Knowledge',
    title:'Claude Code Config & Prompt Engineering', dates:'May 10–16',
    domain:'Domains 3+4 · 40%', color:'#1A50A8', build:'Build: CLAUDE.md hierarchy',
    tasks:[
      {id:'w4d1t1',day:1,date:'May 10',label:'CLAUDE.md',type:'read',domain:'D3',text:'Read Domain 3.1–3.2: CLAUDE.md hierarchy (user → project → directory), @import syntax, .claude/rules/'},
      {id:'w4d2t1',day:2,date:'May 11',label:'Plan Mode',type:'read',domain:'D3',text:'Read Domain 3.3–3.4: Custom slash commands vs skills, plan mode vs direct execution decision criteria'},
      {id:'w4d2t2',day:2,date:'May 11',label:'Plan Mode',type:'build',domain:'D3',text:'Build: full CLAUDE.md hierarchy for a sample project — user-level, project-level, directory-level rules'},
      {id:'w4d3t1',day:3,date:'May 12',label:'CI/CD',type:'read',domain:'D3',text:'Read Domain 3.5–3.6: CI/CD with -p flag, --output-format json, session context isolation in pipelines'},
      {id:'w4d4t1',day:4,date:'May 13',label:'Prompt Eng',type:'read',domain:'D4',text:'Read Domain 4.1–4.3: Explicit criteria, few-shot prompting (2–4 examples), tool_choice: auto vs any vs forced'},
      {id:'w4d4t2',day:4,date:'May 13',label:'Prompt Eng',type:'read',domain:'D4',text:'Read Domain 4.4–4.6: Validation-retry loops, multi-pass review, batch processing (Message Batches API)'},
      {id:'w4d5t1',day:5,date:'May 14',label:'Double Test',type:'test',domain:'D3',text:'Practice Test 4: Claude Code Config (10q) timed. Then Practice Test 5: Prompt Engineering (10q) timed.'},
      {id:'w4d6t1',day:6,date:'May 15',label:'Review',type:'review',domain:'D4',text:'Review all wrong answers. Categorise by domain. Flag prompt engineering "sounds right" traps.'},
      {id:'w4d7t1',day:7,date:'May 16',label:'Rest',type:'rest',domain:'D4',text:'Rest + Anki — add CLAUDE.md hierarchy, tool_choice modes, batch API terms'},
    ],
    materials:[
      {type:'read',icon:'📄',title:'Domain 3: Claude Code Configuration & Workflows',url:'https://claudecertifications.com/claude-certified-architect/domains/claude-code-config',desc:'CLAUDE.md, custom commands, plan mode, CI/CD integration.'},
      {type:'read',icon:'📄',title:'Domain 4: Prompt Engineering & Structured Output',url:'https://claudecertifications.com/claude-certified-architect/domains/prompt-engineering',desc:'Explicit criteria, few-shot, tool_use for structured output, validation loops.'},
      {type:'read',icon:'📚',title:'Anthropic Prompt Engineering Guide',url:'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview',desc:'Official prompting docs. Read structured output and tool_choice sections.'},
      {type:'course',icon:'🎓',title:'Claude Code in Action — full course',url:'https://claudecertifications.com/courses/claude-code-in-action',desc:'15 lessons, 6h. Complete remaining lessons this week.'},
    ],
    concepts:[
      {type:'rule',title:'CLAUDE.md hierarchy',body:'User level: ~/.claude/CLAUDE.md — personal preferences, always loaded\nProject level: ./CLAUDE.md — team rules, committed to repo\nDirectory level: ./src/CLAUDE.md — path-specific rules\n\nLower level overrides higher level for conflicts.'},
      {type:'rule',title:'tool_choice modes',body:'auto — Claude decides whether to use a tool\nany — Claude must use at least one tool\ntool (specific name) — Claude must use exactly that tool\n\nWrong mode = wrong behaviour in structured output pipelines.'},
      {type:'tip',title:'🎯 Exam Tip',body:'If a question involves guaranteed structured output: tool_use with JSON schema is correct. Schema + validation-retry loop, not just instructions.'},
    ]
  },
  {
    id:8, phase:3, phaseLabel:'Exam Prep',
    title:'Context Management + 4 Production Builds', dates:'May 17–23',
    domain:'Domain 5 + All Domains', color:'#2A7A3A', build:'4 non-negotiable build exercises',
    tasks:[
      {id:'w5d1t1',day:1,date:'May 17',label:'Context',type:'read',domain:'D5',text:'Read Domain 5.1–5.3: "lost in the middle" effect, case facts blocks, trimming tool outputs, escalation patterns'},
      {id:'w5d2t1',day:2,date:'May 18',label:'Advanced',type:'read',domain:'D5',text:'Read Domain 5.4–5.6: context degradation, /compact, crash recovery manifests, information provenance'},
      {id:'w5d3t1',day:3,date:'May 19',label:'Build 1',type:'build',domain:'D1',text:'Build Exercise 1: Multi-tool agent with escalation logic — PostToolUse hook + structured error responses'},
      {id:'w5d4t1',day:4,date:'May 20',label:'Build 2',type:'build',domain:'D3',text:'Build Exercise 2: Claude Code team config — full 3-level CLAUDE.md, 2 custom slash commands'},
      {id:'w5d5t1',day:5,date:'May 21',label:'Build 3',type:'build',domain:'D4',text:'Build Exercise 3: Structured data extraction pipeline — tool_use with JSON schema + validation-retry loop'},
      {id:'w5d6t1',day:6,date:'May 22',label:'Build 4',type:'build',domain:'D1',text:'Build Exercise 4: Multi-agent research pipeline — hub-and-spoke with 3 subagents + long-context handoff'},
      {id:'w5d7t1',day:7,date:'May 23',label:'Rest',type:'rest',domain:'D5',text:'Rest + read entire anti-patterns cheatsheet at claudecertifications.com'},
    ],
    materials:[
      {type:'read',icon:'📄',title:'Domain 5: Context Management & Reliability',url:'https://claudecertifications.com/claude-certified-architect/domains/context-management',desc:'Full domain — progressive summarisation risks, escalation, provenance, degradation.'},
      {type:'practice',icon:'⚠️',title:'Anti-Patterns Cheatsheet — all 18 patterns',url:'https://claudecertifications.com/claude-certified-architect/anti-patterns',desc:'Read fully on Day 7. These are the exam distractors.'},
      {type:'practice',icon:'🎬',title:'6 Exam Scenarios — scenario walkthroughs',url:'https://claudecertifications.com/claude-certified-architect/scenarios',desc:'All 6 production scenarios. Study before Mock Exam 1.'},
      {type:'supplementary',icon:'📝',title:'Hightower CCA Guide — Parts 3–8',url:'https://pub.towardsai.net/claude-certified-architect-the-complete-guide-to-passing-the-cca-foundations-exam-9665ce7342a8',desc:'Deep dives on the 6 hardest exam scenarios.'},
    ],
    concepts:[
      {type:'rule',title:'Lost in the middle — context positioning',body:'Claude\'s attention is strongest at the start and end of context.\nCritical facts placed in the middle get ignored.\n\nFix: use case facts blocks at the top, keep recency at the bottom.'},
      {type:'tip',title:'🎯 Exam Tip',body:'The 4 build exercises are not optional. Every domain tests architectural judgment under production failure conditions — you cannot fake that from reading alone.'},
    ]
  },
  {
    id:9, phase:3, phaseLabel:'Exam Prep',
    title:'3 Full Mock Exams → Exam Day', dates:'May 24–30',
    domain:'All 5 Domains', color:'#1A5A2A', build:'Exam: May 30 · 60q · 120min',
    tasks:[
      {id:'w6d1t1',day:1,date:'May 24',label:'Mock 1',type:'test',domain:'D1',text:'Full Mock Exam 1 — 50 questions, 100-min strict timer, all 6 scenarios. No pausing, no lookups.'},
      {id:'w6d2t1',day:2,date:'May 25',label:'Analysis',type:'review',domain:'D1',text:'Analyse Mock 1 by domain — count misses per domain, not per question. Identify your 2 weakest.'},
      {id:'w6d2t2',day:2,date:'May 25',label:'Analysis',type:'build',domain:'D1',text:'Targeted lab: rebuild the exercise from Week 5 that matches your weakest domain'},
      {id:'w6d3t1',day:3,date:'May 26',label:'Remediation',type:'review',domain:'D1',text:'Re-read the full domain page for your weakest domain + anti-patterns for that domain specifically'},
      {id:'w6d4t1',day:4,date:'May 27',label:'Mock 2',type:'test',domain:'D1',text:'Full Mock Exam 2 — 50 questions, 100-min timer. Track domain-by-domain improvement vs Mock 1.'},
      {id:'w6d5t1',day:5,date:'May 28',label:'Mock 3',type:'test',domain:'D1',text:'Full Mock Exam 3 — final dress rehearsal. Same conditions as exam day.'},
      {id:'w6d6t1',day:6,date:'May 29',label:'Light Review',type:'review',domain:'D1',text:'Anti-patterns cheatsheet only — light read, no new learning. Stop studying by 8pm.'},
      {id:'w6d7t1',day:7,date:'May 30',label:'🎯 EXAM DAY',type:'test',domain:'D1',text:'Claude Certified Architect Foundations Exam — 60 questions, 120 minutes. You\'ve done the work. Execute.'},
    ],
    materials:[
      {type:'practice',icon:'❓',title:'Practice Questions — claudecertifications.com',url:'https://claudecertifications.com/claude-certified-architect/practice-questions',desc:'Use as Mock 1 base. Do all questions in one timed sitting.'},
      {type:'practice',icon:'🎬',title:'6 Scenario Walkthroughs',url:'https://claudecertifications.com/claude-certified-architect/scenarios',desc:'Review all 6 before each mock exam.'},
      {type:'practice',icon:'⚠️',title:'Anti-Patterns Cheatsheet — final read Day 6',url:'https://claudecertifications.com/claude-certified-architect/anti-patterns',desc:'Your last study material. Read it once on May 29, then close the books.'},
      {type:'read',icon:'🎓',title:'Register for Exam — Anthropic Skilljar',url:'https://anthropic.skilljar.com/claude-certified-architect-foundations-access-request',desc:'If not already registered, do this NOW on Day 1 of Week 9.'},
      {type:'supplementary',icon:'🎬',title:'Anthropic CCA - 3 Full Practice Exams (Frank Kane)',url:'https://www.udemy.com/course/anthropic-claude-certified-architect-3-full-practice-exams/',desc:'Optional · Udemy · ⭐4.3 · 180 scenario-based questions with detailed explanations.',paid:true},
      {type:'supplementary',icon:'🎬',title:'Claude Certified Architect Exams - 6 Practice Tests',url:'https://www.udemy.com/course/claude-certified-architect-practice-tests/',desc:'Optional · Udemy · ⭐4.6 Bestseller · 360 questions. Best-rated CCA practice test pack.',paid:true},
      {type:'supplementary',icon:'🎬',title:'NEW CCAF Exams 2026 — 300 Questions',url:'https://www.udemy.com/course/new-claude-certified-architect-foundations-cca-f-exams/',desc:'Optional · Udemy · ⭐4.2 · 300 questions. Updated 2026 content.',paid:true},
    ],
    concepts:[
      {type:'rule',title:'Exam day strategy',body:'First pass: Answer confident questions immediately. Flag uncertain ones.\nSecond pass: Eliminate 2 wrong answers first, then choose between 2.\nThird pass: Check flagged — first instinct is usually right.\nTime: 120 min / 60 questions = 2 min each. You have buffer.'},
      {type:'rule',title:'Elimination strategy',body:'1. Eliminate any answer using NL for loop control → wrong\n2. Eliminate any answer using prompt for business rule enforcement → wrong\n3. Eliminate any answer sharing full coordinator context with subagents → wrong\n4. Eliminate any answer using flat multi-agent for complex tasks → wrong'},
      {type:'tip',title:'🎯 Final Tip',body:'When stuck, ask: "What would fail in production with this choice?" The answer that avoids production failure is almost always correct.'},
    ]
  }
]

export const QUIZ_QUESTIONS = [
  {id:'q1',domain:'D1',question:'What is the correct mechanism for controlling an agentic loop in the Claude API?',options:['Parse the assistant\'s text output for phrases like "task complete"','Check the stop_reason field in the API response','Set an arbitrary maximum iteration count as the primary stopping condition','Monitor token usage and stop when a threshold is reached'],correct:1,explanation:'stop_reason is the only reliable loop control signal. "tool_use" means Claude wants to act; "end_turn" means Claude is done. Parsing text is an anti-pattern — Claude may phrase completions differently.'},
  {id:'q2',domain:'D1',question:'After a tool executes in an agentic loop, what must happen before the next API call?',options:['Start a new conversation with fresh context','Append the tool_result to the messages array','Clear the messages array to save tokens','Convert the tool output to a system prompt'],correct:1,explanation:'Tool results must be appended as a user message with type "tool_result" and the matching tool_use_id. Without this, Claude has no knowledge of what the tool returned.'},
  {id:'q3',domain:'D1',question:'In a hub-and-spoke multi-agent system, what context should a coordinator pass to a subagent?',options:['The full coordinator conversation history','Only the context specific and relevant to that subagent\'s task','No context — subagents retrieve what they need independently','A summary of all previous subagent results'],correct:1,explanation:'Subagents should receive only task-specific context. Sharing full coordinator history wastes tokens and confuses the subagent with irrelevant information — a critical anti-pattern.'},
  {id:'q4',domain:'D1',question:'A customer service agent must never process refunds over $500. How should this be enforced?',options:['Add "IMPORTANT: Never process refunds over $500" to the system prompt','Use a PostToolUse hook that blocks the refund and escalates','Train the model with examples of correct refund handling','Use a pre-prompt reminder before each refund request'],correct:1,explanation:'Critical business rules require programmatic enforcement via hooks — they are deterministic. Prompt-based instructions are probabilistic; the model can and sometimes will ignore them.'},
  {id:'q5',domain:'D2',question:'A tool returns an error because an external API is temporarily unavailable. Which error response structure is correct?',options:['{ "error": "API unavailable" }','{ "isError": true, "errorCategory": "rate_limited", "isRetryable": true }','{ "isError": true, "message": "try again later" }','{ "status": 503, "retry": true }'],correct:1,explanation:'Structured error responses require all three fields: isError signals failure, errorCategory categorises the failure type, and isRetryable tells the agent whether automatic retry is appropriate.'},
  {id:'q6',domain:'D2',question:'You need to search file names matching a pattern across a codebase. Which built-in tool do you use?',options:['Grep','Glob','Find','Read'],correct:1,explanation:'Glob matches file paths using pattern syntax (e.g., **/*.py). Grep searches file content for text patterns. Using Grep to find files by name is a common anti-pattern.'},
  {id:'q7',domain:'D2',question:'An MCP server should be available to all developers on a team. Where should the MCP configuration be stored?',options:['~/.claude.json (user-level config)','.mcp.json in the project root (project-level config)','In an environment variable','In the system CLAUDE.md file'],correct:1,explanation:'.mcp.json is project-level and committed to the repository, making it shared with the team. ~/.claude.json is user-level and personal.'},
  {id:'q8',domain:'D3',question:'You want directory-specific rules to override project rules for files in the /src/api folder. Which approach is correct?',options:['Duplicate the project CLAUDE.md in /src/api with modifications','Create /src/api/CLAUDE.md with YAML frontmatter specifying glob patterns','Use @import to pull in directory-specific overrides from the root CLAUDE.md','Add path-specific rules directly to the user-level CLAUDE.md'],correct:1,explanation:'Directory-level CLAUDE.md files with YAML frontmatter containing paths glob patterns allow path-specific rule overrides.'},
  {id:'q9',domain:'D3',question:'You want Claude Code to operate non-interactively in a CI/CD pipeline. Which flag enables this?',options:['--non-interactive','--ci-mode','-p (print mode)','--batch'],correct:2,explanation:'The -p flag enables print/non-interactive mode for Claude Code, allowing it to run without human input in automated pipelines.'},
  {id:'q10',domain:'D4',question:'You need Claude to always return output in a specific JSON schema with guaranteed compliance. Which approach works best?',options:['Add "respond in JSON format" to the system prompt','Use tool_use with a JSON schema definition as the tool input schema','Ask Claude to validate its own output after generation','Use few-shot examples of correct JSON output only'],correct:1,explanation:'tool_use with a JSON schema guarantees schema compliance at the structural level. Prompt instructions produce JSON that may have semantic errors.'},
  {id:'q11',domain:'D4',question:'A validation step finds an error in Claude\'s structured output. How should the retry prompt be constructed?',options:['Restart the conversation from the beginning','Append the specific validation errors to the existing conversation and request correction','Ask Claude to "try again" without additional context','Switch to a different model for the retry attempt'],correct:1,explanation:'Appending specific errors to the prompt gives Claude exactly what it needs to correct its output. Vague "try again" requests often produce the same error.'},
  {id:'q12',domain:'D5',question:'In a long-context conversation, where should critical reference information be positioned?',options:['In the middle of the context for balanced attention','At the beginning or end of the context','Distributed evenly throughout for consistent access','In a separate system prompt attachment'],correct:1,explanation:'Claude\'s attention is strongest at the start and end of context — the "lost in the middle" effect. Critical facts should be positioned at the start or end, never buried in the middle.'},
  {id:'q13',domain:'D1',question:'A coordinator agent needs to run two research subagents simultaneously. How is parallel execution achieved?',options:['Call the Task tool twice in separate API requests','Include two Task tool calls in a single API response','Use fork_session before each subagent call','Configure the coordinator\'s concurrency settings'],correct:1,explanation:'Multiple Task tool calls in a single API response trigger parallel subagent execution. Sequential API requests would execute them serially.'},
  {id:'q14',domain:'D0',question:'A language model confidently states an incorrect fact without any uncertainty. What term describes this behaviour?',options:['Overfitting','Hallucination','Context overflow','Temperature spike'],correct:1,explanation:'Hallucination is when a model generates confident but incorrect or fabricated information. It is a fundamental limitation of LLMs — systems should verify critical outputs rather than blindly trust them.'},
  {id:'q15',domain:'D0',question:'You want Claude to always answer in a specific persona with consistent rules across all user messages. Where should these instructions go?',options:['In every user message as a reminder','In the system prompt','In a tool description','In the assistant\'s first response'],correct:1,explanation:'The system prompt is the correct place for persistent instructions, persona, and constraints. It is set once and applies to the entire conversation.'},
  {id:'q16',domain:'D0',question:'Which prompting technique provides Claude with 2–3 examples of the desired input/output format before the actual request?',options:['Chain-of-thought prompting','Zero-shot prompting','Few-shot prompting','Role prompting'],correct:2,explanation:'Few-shot prompting provides examples of the desired behaviour in the prompt. It is one of the most effective techniques for getting consistent output format and style.'},
  {id:'q17',domain:'D0',question:'A prompt asks Claude to "think step by step before answering". Which technique is this?',options:['Few-shot prompting','Role prompting','Chain-of-thought prompting','XML structuring'],correct:2,explanation:'Chain-of-thought prompting encourages Claude to reason through a problem step-by-step before giving a final answer, improving accuracy on complex reasoning tasks.'},
  {id:'q18',domain:'DA',question:'You are building a RAG system where document knowledge changes frequently. Why is RAG preferred over fine-tuning for this use case?',options:['RAG is cheaper to set up initially','RAG retrieves current information at query time without retraining','Fine-tuning does not support document retrieval','RAG uses less context window'],correct:1,explanation:'RAG retrieves relevant chunks at query time, so the knowledge base stays current without retraining. Fine-tuning bakes knowledge into model weights, making it stale as data changes.'},
  {id:'q19',domain:'DA',question:'In the Claude Messages API, what field tells you whether Claude wants to use a tool or has finished responding?',options:['response.type','response.status','response.stop_reason','response.finish_reason'],correct:2,explanation:'stop_reason is the field that indicates why Claude stopped. "tool_use" means Claude wants to call a tool; "end_turn" means Claude has finished its response.'},
  {id:'q20',domain:'DA',question:'You need Claude to process 1000 independent documents overnight with no real-time response needed. Which API feature is most cost-effective?',options:['Streaming API with parallel requests','Message Batches API','Prompt caching with repeated calls','Multiple concurrent API keys'],correct:1,explanation:'The Message Batches API is designed for large-scale async processing. It offers significant cost savings over real-time requests for workloads that don\'t require immediate responses.'},
  {id:'q21',domain:'D0',question:'What is the primary risk of placing critical reference facts in the middle of a very long Claude context?',options:['Claude will refuse to process long contexts','The facts may receive less attention due to the "lost in the middle" effect','Tokens in the middle cost more to process','Claude truncates content from the middle first'],correct:1,explanation:'The "lost in the middle" effect means Claude\'s attention is strongest at the start and end of context. Critical facts buried in the middle may be underweighted, leading to errors.'},
  {id:'q22',domain:'D0',question:'Which of these is a responsible use principle when deploying Claude in a customer-facing application?',options:['Remove all safety guardrails to maximise helpfulness','Always verify Claude\'s outputs for high-stakes decisions rather than acting on them automatically','Hide the fact that users are interacting with AI','Disable system prompts to give users full model access'],correct:1,explanation:'Responsible AI deployment requires human oversight for high-stakes decisions. Claude\'s outputs should be verified, not blindly acted upon, especially in consequential domains.'},
]
